<aside class="info__bio">
  <h3>Bio</h3>

  <p class="hello">
    Hello, I'm Csongor, web designer and developer from Europe.
  </p>

  <p class="statement">
    I like to handcraft websites assembling as much art as engineering.
  </p>

  <p class="contact">
    Let's <a class="link" href="mailto:bartus.csongor@gmail.com" title="bartus.csongor@gmail.com">bartus.csongor@gmail.com</a> play together and deliver a message.
  </p>
</aside>
